env: halfcheetah
timesteps: 2000000
seed: 44
demo_episodes: 100
learner:
  algorithm: TRPO
  policy: MlpPolicy
reward_net:
  type: BasicRewardNet
  hid_sizes:
  - 256
  - 256
  - 128
  normalize_input_layer: RunningNorm
gail_trainer:
  demo_batch_size: 2048
  gen_replay_buffer_capacity: 2048
  n_disc_updates_per_round: 16
  disc_opt_kwargs:
    lr: 0.0003
  allow_variable_horizon: true
